version: '3'

services:
  mysqlsrv:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: "liv290304"
      MYSQL_DATABASE: "geren849_ciweb"
    ports:
      - "3306:3306"
    volumes:
      - /home/jorge/Projects/etl/Volumes/Docker/Mysql:/var/lib/mysql
    networks:
      - mysql-compose-network
  
networks: 
  mysql-compose-network:
    driver: bridge